### ISSUE TITLE
Unable to run the script alone due to a wrong shebang?

### ISSUE THREAD

**Issue by alexarnaud** [chrys87/ocrdesktop#3]
Hello all,

When you try to run the ocrdesktop script like this:
./ocridesktop

You will obtain the following error:
bash: ./ocrdesktop: /bin/python3: bad interpreter: No such file or directory

On Debian, the python3 binary is on "/usr/bin/python3". I assume it's the same on Arch, can you confirm this to me? If yes, I could send you a pull request to fix that or you could do that yourself as the change looks easy to do..

Best regards.

**Comment by chrys87** [comment]
Howdy,
i changed it to
#!/usr/bin/python3
cheers chrys
